<?php

namespace Container8FtJGOD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LpTB6LNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LpTB6LN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LpTB6LN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'bus' => '?',
            'slugger' => '?',
        ]);
    }
}
