<?php

namespace Container1MSXkug;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormMessageHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\MessageHandler\FormMessageHandler' shared autowired service.
     *
     * @return \App\MessageHandler\FormMessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'MessageHandler'.\DIRECTORY_SEPARATOR.'FormMessageHandler.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\MessageHandler\\FormMessageHandler'])) {
            return $container->privates['App\\MessageHandler\\FormMessageHandler'];
        }

        return $container->privates['App\\MessageHandler\\FormMessageHandler'] = new \App\MessageHandler\FormMessageHandler($a);
    }
}
