<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1MSXkug\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1MSXkug/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1MSXkug.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1MSXkug\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1MSXkug\App_KernelDevDebugContainer([
    'container.build_hash' => '1MSXkug',
    'container.build_id' => 'b37da0e3',
    'container.build_time' => 1710354823,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1MSXkug');
